include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    sort_pub_dependencies: ignore
    directives_ordering: false

  exclude: [
    '**/mason/**',
    '**/*.freezed.dart',
    '**/*.g.dart',
  ]
