name: dismantling
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic_mono: ^1.19.2
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4
  intersperse: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

import_sorter:
  comments: false
