name: dismantling
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic_mono: ^1.24.0+1
  freezed_annotation: ^2.4.1
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.5
  intersperse: ^2.0.0
  riverpod_annotation: ^2.3.3
  mason: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  freezed: ^2.4.5
  import_sorter: ^4.6.0
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

import_sorter:
  comments: false
