name: dismantling
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic_mono: ^1.30.3
  freezed_annotation: ^3.0.0
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  intersperse: ^2.0.0
  riverpod_annotation: ^2.6.1
  mason: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  freezed: ^3.0.6
  import_sorter: ^4.6.0
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true

import_sorter:
  comments: false
