name: dismantling
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic_mono: ^1.19.2
  freezed_annotation: ^1.1.0
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.8
  freezed: ^1.1.1

flutter:

  uses-material-design: true
